name: Build and Push Docker Image to ACR
on:
  push:
    branches:
      - master
jobs:
  build-and-push-to-acr:
    name: Build Docker Image and Push to ACR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Log in to Azure Container Registry
        env:
          AZURE_LOGIN_SERVER: ${{ secrets.AZURE_LOGIN_SERVER }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        run: |
          echo "${AZURE_PASSWORD}" | docker login "${AZURE_LOGIN_SERVER}" -u "${AZURE_USERNAME}" --password-stdin
      - name: Build Docker Image
        run: |
          docker build -t "${{ secrets.AZURE_LOGIN_SERVER }}/todo:latest" .
      - name: Push Docker Image to ACR
        run: |
          docker push "${{ secrets.AZURE_LOGIN_SERVER }}/todo:latest"
      - name: Log out of ACR
        run: docker logout










