name: Build and Deploy to Azure VM

on:
  push:
    branches:
      - master  # Run workflow on pushes to the master branch

jobs:
  build-and-push-to-acr:
    name: Build Docker Image and Push to ACR
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Verify ACR Login Secrets
        run: |
          echo "AZURE_LOGIN_SERVER=${{ secrets.AZURE_LOGIN_SERVER }}"
          echo "AZURE_USERNAME is set"
          echo "AZURE_PASSWORD is set"

      - name: Log in to Azure Container Registry
        env:
          AZURE_LOGIN_SERVER: ${{ secrets.AZURE_LOGIN_SERVER }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        run: |
          docker login $AZURE_LOGIN_SERVER -u $AZURE_USERNAME -p $AZURE_PASSWORD

      - name: Build and Push Docker Image to ACR
        run: |
          docker build -t ${{ secrets.AZURE_LOGIN_SERVER }} todo:latest .
          docker push ${{ secrets.AZURE_LOGIN_SERVER }} todo:latest

      - name: Log out of ACR
        run: docker logout ${{ secrets.AZURE_LOGIN_SERVER }}

  deploy-to-azure-vm:
    name: Deploy Docker Container on Azure VM
    runs-on: self-hosted  # Self-hosted runner on Azure VM
    needs: build-and-push-to-acr

    steps:
      - name: Log in to Azure Container Registry
        env:
          AZURE_LOGIN_SERVER: ${{ secrets.AZURE_LOGIN_SERVER }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        run: |
          docker login $AZURE_LOGIN_SERVER -u $AZURE_USERNAME -p $AZURE_PASSWORD

      - name: Stop Existing Container
        run: |
          if [ "$(docker ps -q -f name=todolist)" ]; then
            docker stop todolist
            docker rm todolist
          fi

      - name: Pull Docker Image from ACR
        run: docker pull ${{ secrets.AZURE_LOGIN_SERVER }} todo:latest

      - name: Run Docker Container
        run: |
          docker run -d --name todolist -p 4000:4000 ${{ secrets.AZURE_LOGIN_SERVER }} todo:latest

      - name: Log out of ACR
        run: docker logout ${{ secrets.AZURE_LOGIN_SERVER }}
