name: Build and Deploy to Azure VM
on:
  push:
    branches:
      - master
jobs:
  build-and-push-to-acr:
    name: Build Docker Image and Push to ACR
    runs-on: ubuntu-latest  # GitHub-hosted runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Docker CLI (disable buildx)
        run: |
          docker build --help  # Check if Docker CLI works as expected
      - name: Log in to Azure Container Registry
        env:
          AZURE_LOGIN_SERVER: ${{ secrets.AZURE_LOGIN_SERVER }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        run: |
          echo $AZURE_PASSWORD | docker login $AZURE_LOGIN_SERVER -u $AZURE_USERNAME --password-stdin
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.AZURE_LOGIN_SERVER }}/todo:latest .
      - name: Push Docker Image to ACR
        run: |
          docker push ${{ secrets.AZURE_LOGIN_SERVER }}/todo:latest
      - name: Log out of ACR
        run: docker logout
  deploy-to-azure-vm:
    name: Deploy Docker Container on Azure VM
    runs-on: self-hosted  # Self-hosted runner on Azure VM
    needs: build-and-push-to-acr
    steps:
      - name: Check Docker version on self-hosted runner
        run: docker --version  # Verify Docker version on self-hosted runner
      - name: Log in to Azure Container Registry
        env:
          AZURE_LOGIN_SERVER: ${{ secrets.AZURE_LOGIN_SERVER }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
        run: |
          echo $AZURE_PASSWORD | docker login $AZURE_LOGIN_SERVER -u $AZURE_USERNAME --password-stdin
      - name: Pull Docker Image from ACR
        run: docker pull ${{ secrets.AZURE_LOGIN_SERVER }}/todo:latest
      - name: Run Docker Container
        run: |
          docker run -d --name todolist -p 4000:4000 ${{ secrets.AZURE_LOGIN_SERVER }}/todo:latest
      - name: Log out of ACR
        run: docker logout












